In [1]:
import numpy as np
import pandas as pd #для работы с данными
import scipy.stats #для работы со статистикой
import matplotlib.pyplot as plt #для визуализации результатов

In [2]:
data = pd.read_csv('/Users/irinanikulina/Documents/ML/LinearRegression/adult.csv')
data.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18          ?  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                  ?    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              48842 non-null  int64 
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64 
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64 
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64 
 11  capital-loss     48842 non-null  int64 
 12  hours-per-week   48842 non-null  int64 
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB


In [4]:
data.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18          ?  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                  ?    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [5]:
data[ pd.isnull(data['age'])].head()

Empty DataFrame
Columns: [age, workclass, fnlwgt, education, educational-num, marital-status, occupation, relationship, race, gender, capital-gain, capital-loss, hours-per-week, native-country, income]
Index: []

In [6]:
data['age'].unique()

array([25, 38, 28, 44, 18, 34, 29, 63, 24, 55, 65, 36, 26, 58, 48, 43, 20,
       37, 40, 72, 45, 22, 23, 54, 32, 46, 56, 17, 39, 52, 21, 42, 33, 30,
       47, 41, 19, 69, 50, 31, 59, 49, 51, 27, 57, 61, 64, 79, 73, 53, 77,
       80, 62, 35, 68, 66, 75, 60, 67, 71, 70, 90, 81, 74, 78, 82, 83, 85,
       76, 84, 89, 88, 87, 86])

In [7]:
data = data[ pd.isnull(data['age'])==0]

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              48842 non-null  int64 
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64 
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64 
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64 
 11  capital-loss     48842 non-null  int64 
 12  hours-per-week   48842 non-null  int64 
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 6.0+ MB


In [9]:
from sklearn.linear_model import LogisticRegression

In [23]:
selectedColumns = data[['age','workclass','marital-status','educational-num','income']]

In [24]:
X = pd.get_dummies(selectedColumns, columns = ['workclass','marital-status'])
del X['income']
print('пометили единичкой тип занятости, семейное положение')
X.head()

пометили единичкой тип занятости, семейное положение


age  educational-num  workclass_?  workclass_Federal-gov  \
0   25                7            0                      0   
1   38                9            0                      0   
2   28               12            0                      0   
3   44               10            0                      0   
4   18               10            1                      0   

   workclass_Local-gov  workclass_Never-worked  workclass_Private  \
0                    0                       0                  1   
1                    0                       0                  1   
2                    1                       0                  0   
3                    0                       0                  1   
4                    0                       0                  0   

   workclass_Self-emp-inc  workclass_Self-emp-not-inc  workclass_State-gov  \
0                       0                           0                    0   
1                       0                           0                    0   
2                       0                           0                    0   
3                       0                           0                    0   
4                       0                           0                    0   

   workclass_Without-pay  marital-status_Divorced  \
0                      0                        0   
1                      0                        0   
2                      0                        0   
3                      0                        0   
4                      0                        0   

   marital-status_Married-AF-spouse  marital-status_Married-civ-spouse  \
0                                 0                                  0   
1                                 0                                  1   
2                                 0                                  1   
3                                 0                                  1   
4                                 0                                  0   

   marital-status_Married-spouse-absent  marital-status_Never-married  \
0                                     0                             1   
1                                     0                             0   
2                                     0                             0   
3                                     0                             0   
4                                     0                             1   

   marital-status_Separated  marital-status_Widowed  
0                         0                       0  
1                         0                       0  
2                         0                       0  
3                         0                       0  
4                         0                       0

In [25]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [26]:
le.fit(data['income'])

LabelEncoder()

In [27]:
le.classes_

array(['<=50K', '>50K'], dtype=object)

In [28]:
le.transform(['<=50K', '>50K','<=50K'])

array([0, 1, 0])

In [29]:
le.inverse_transform([0, 1])

array(['<=50K', '>50K'], dtype=object)

In [30]:
#у = преобразованный столбец income
y = pd.Series (data = le.transform(data['income']))
y.head()

0    0
1    0
2    1
3    1
4    0
dtype: int64

In [93]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

model = make_pipeline(StandardScaler(),LogisticRegression(max_iter=1000))

In [94]:
model = LogisticRegression()

In [95]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [96]:
model.fit(X_train,y_train)
predictions = model.predict(X_test)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [97]:
predictions[:5]

array([0, 0, 0, 0, 1])

In [98]:
model.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0])

In [99]:
model.predict_proba(X_test)

array([[0.92626363, 0.07373637],
       [0.77319094, 0.22680906],
       [0.79130576, 0.20869424],
       ...,
       [0.89078293, 0.10921707],
       [0.66653316, 0.33346684],
       [0.95818207, 0.04181793]])

In [100]:
model.score(X_train,y_train)

0.8208780601947995

In [101]:
model.score(X_test,y_test)

0.8296594554016242

In [92]:
from sklearn.svm import SVC

In [48]:
clf = make_pipeline(StandardScaler(),SVC(gamma='auto'))

In [49]:
clf.fit(X_train,y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(gamma='auto'))])

In [50]:
clf.score(X_train,y_train)

0.8236889923988432

In [51]:
clf.score(X_test,y_test)

0.8284368922100522

In [52]:
svc = SVC(gamma='auto')
svc.fit(X_train,y_train)

SVC(gamma='auto')

In [53]:
svc.score(X_train,y_train)

0.8261203388529164

In [54]:
svc.score(X_test,y_test)

0.8324291124987204